### ISSUE TITLE
Model file is missing

### ISSUE THREAD

**Issue by wenfs** [machanic/SimulatorAttack#1]
Hello, I run the code here and report an error. Can you provide a download link of the model file?

self.meta_model_path = "{root}/train_pytorch_model/meta_simulator/{meta_train_type}@{dataset}@{split}@model_{meta_arch}@loss_{loss}@dataloss_{data_loss}_{norm}_{target_str}*@without_resnet.pth.tar"

**Comment by machanic** [comment]
I will upload the model file to cloud disk and update the README file to provide more instructions soon!

**Comment by machanic** [comment]
@wenfs Now I have uploaded all the trained models to [this link](https://cloud.tsinghua.edu.cn/d/a11beb12358b416199b9/) so that you can download. Also, the target models are uploaded in [this link](https://cloud.tsinghua.edu.cn/d/a11beb12358b416199b9/).

**Comment by machanic** [comment]
Sorry for delay, I have uploaded all the models (including the models used in the training) to [Tsinghua Cloud Disk](https://cloud.tsinghua.edu.cn/d/a11beb12358b416199b9/).
You can download them.
