### ISSUE TITLE
backbone

### ISSUE THREAD

**Issue by wsprogrammeryang** [machanic/SimulatorAttack#2]
hello,
you select ResNet-34  as the backbone of the Simulator. why is it?
is there any requirement for the backbone?

**Comment by machanic** [comment]
ResNet-34 is not a very large network, so it can work well in meta-learning when using only a few data to fine-tune it. Besides, the fine-tuning requires time, and a small network will be faster.

**Comment by wsprogrammeryang** [comment]
i got it.
thanks!
